version: '3.8'

services:
  db:
    image: postgres:16
    container_name: todolist_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: todolist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: todolist_backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_DATABASE=todolist
      - DB_PASSWORD=123
      - DB_PORT=5432
      - JWT_SECRET=123456

  frontend:
    build: ./frontend
    container_name: todolist_frontend
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3000
      - PORT=3001

volumes:
  postgres_data:
